language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"

matrix:
  allow_failures:
    - python: "pypy3"
    - python: "3.7-dev"

install:
  - python -m pip install numpy ipython
  - python -m pip install .
script:
  - make test

sudo: false
